Fix popup window position
cxxxr/lem pull request #525
Opened 2020-10-03 03:09 UTC by Hamayama

ポップアップ画面の表示位置を修正しました。
(画面の端で表示させると、はみ出してスクロールしてしまったり (PDCursesだけかも)、
補完の候補をしぼりこむときに、上にずれて表示される 等)

2020-10-04 02:40 UTC, Hamayama commented
すいません右上の計算が、ウィンドウの右上ではなく、
画面全体の右上になっていました。

2020-10-05 14:48 UTC, cxxxr commented
改善点がよくわかりませんでした
変更前と変更後の視覚的に差分が見たいです

2020-10-05 15:18 UTC, Hamayama commented
変更前の画面をキャプチャしました。
(1) popup がはみ出す例
(PDCurses 側でいろいろガードしたので、スクロールはしなくなりましたが、
元々は折り返し表示でスクロールが発生して、表示が崩れていました)
![popup1](https://user-images.githubusercontent.com/4497079/95096881-c995dd80-0767-11eb-898f-6eb9f221bfa0.png)
(2) 補完の候補をしぼりこむときに、上にずれて表示される例
(候補を表示させた後、続けて入力して絞り込むと、
popup が1行上にずれて、入力を覆い隠していました)
![popup2](https://user-images.githubusercontent.com/4497079/95096888-cbf83780-0767-11eb-97ad-94d5c4239b17.png)

2020-10-05 15:30 UTC, Hamayama commented
変更後のキャプチャです。
![popup1A](https://user-images.githubusercontent.com/4497079/95099562-fb5c7380-076a-11eb-8a87-ac8f2a712542.png)
![popup2A](https://user-images.githubusercontent.com/4497079/95099563-fd263700-076a-11eb-9be8-e40820c9741f.png)

2020-10-05 16:46 UTC, cxxxr requested changes

2020-10-05 16:46 UTC, cxxxr commented on lib/core/popup-window.lisp
> +               (window-cursor-x source-window)))
ここのwindow-cursor-xで問題がある気がします

find-fileで補完を出した瞬間のポップアップ
![スクリーンショット 2020-10-06 1 42 11](https://user-images.githubusercontent.com/13656378/95107749-49767480-0775-11eb-839c-c675073d615f.png)

一文字入力した後のポップアップ
![スクリーンショット 2020-10-06 1 42 16](https://user-images.githubusercontent.com/13656378/95107760-4da29200-0775-11eb-9c74-a0fb1cb45c10.png)

期待する挙動としてはカーソルの右下がポップアップウィンドウの左上になってほしいです

2020-10-05 16:57 UTC, cxxxr commented on lib/core/popup-window.lisp
> +         (disp-w (max (- (display-width)  b2 #+win32 2)
win32上でelectornなどの別のfrontendを使う場合も影響しそうですし、アドホックな処理をここに挟むのは好ましく無いので、できればpdcursesのfrontend側でオーバーライドするようにしてほしいです

2020-10-05 16:58 UTC, cxxxr commented
キャプチャでの説明ありがとうございます
(2)については困っていて直さないといけないと思ってたので助かります

2020-10-06 02:20 UTC, Hamayama commented
以下の件を修正しました。

1. M-x find-file で補完候補をしぼりこむときに、ポップアップの表示が左にずれる件
   原因は、find-file の buffer の truncate-lines が nil になっていないことでした。
   (すなわち、折り返しのある buffer と認識されていました。
   そして、文字を入力すると、画面の端に到達したので折り返しが発生したと、
   window-cursor-x が判定するため、X座標が 0 になっていました)
   
   それで、file.lisp の find-file-buffer のところに
   `(setf (variable-value 'truncate-lines :buffer buffer) nil)`
   を入れてみたのですが、効果がありませんでした。
   
   原因は、prompt-window.lisp の prompt-mode への移行がメジャーモードであるため、
   そこで変数がリセットされるためでした。
   
   このため、(define-major-mode prompt-mode ... の方に、
   `(setf (variable-value 'truncate-lines :buffer (current-buffer)) nil)`
   を入れるように変更しました。これで直ったようです。

2. lem-pdcurses 用のマージンの設定について
   popup-window.lisp に、`*extra-right-margin*` と `*extra-width-margin*` を追加して、
   lem-pdcurses の方から、これらの変数をセットするようにしました。
   (lem-pdcurses の方は、ちょうど別のプルリクエストも出しているので、
   こちらには含めませんでした)

2020-10-07 14:41 UTC, merged

2020-10-07 14:41 UTC, cxxxr commented
ありがとうございます